---
title: Ground Source
phone: "(555)555-5555"
email: your-email@example.com
address: 1157 Highland Ave, Los Angeles, CA 90028
instagram: groundsource
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-multipost
gems:
- jekyll-babel
- jekyll-autoprefixer
- jekyll-multipost
collections:
  listings:
    output: true
    layout: listing
    scope: 
    values:
      layout: listing
  testimonials: 
  agents: 
  case_studies: 
  examples_investment: 
  examples_landlord: 
  examples_tenant: 
timezone: America/Los_Angeles
