---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _case_studies
  label: Case_studies
  create: all
  match: "**/*"
- type: directory
  path: _listings
  label: Listings
  create: all
  match: "**/*"
- type: directory
  path: _testimonials
  label: Testimonials
  create: all
  match: "**/*"
- type: directory
  path: _agents
  label: Agents
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: false
file_template: ":filename:"
