---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections:
- path: _case_studies
  label: Case_studies
  create: all
- path: _listings
  label: Listings
  create: all
- path: _testimonials
  label: Testimonials
  create: all
- path: _agents
  label: Agents
  create: all
- path: _posts
  label: Posts
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: false
file_template: ":filename:"
